- name: Download .deb
  ansible.builtin.get_url:
    url: "{{ item.value.url }}"
    checksum: "{{ item.value.checksum if 'checksum' in item.value else '' }}"
    dest: "{{ item.value.filename }}"
    mode: 0755
  when: item.value.package not in ansible_facts.packages

- name: Install .deb
  become: true
  ansible.builtin.apt:
    deb: "{{ item.value.filename }}"
  when: item.value.package not in ansible_facts.packages
