- name: Install GNOME packages
  become: yes
  ansible.builtin.package:
    name:
      - gnome-shell
      - gnome-shell-extensions
      - gnome-shell-extension-manager

- name: Dconf entries
  community.general.dconf:
    key: "{{ item.value.key }}"
    value: "{{ item.value.value }}"
  loop: "{{ dconf_entries | dict2items }}"

# Loading terminal preferences via the dconf module is tedious and hard to maintain,
# so using a .dconf file and loading that instead seems better
- name: Write terminal preferences to file
  vars:
    terminal_prefs: |
      [/]
      default='8481259a-b760-4d77-a61e-9d0d255732ce'
      list=['8481259a-b760-4d77-a61e-9d0d255732ce']

      [:8481259a-b760-4d77-a61e-9d0d255732ce]
      audible-bell=false
      background-color='#2E3440'
      background-transparency-percent=15
      bold-color='#D8DEE9'
      bold-color-same-as-fg=true
      cursor-background-color='rgb(216,222,233)'
      cursor-colors-set=true
      cursor-foreground-color='rgb(59,66,82)'
      custom-command='/usr/bin/fish'
      font='UbuntuMono Nerd Font Mono 20'
      foreground-color='#D8DEE9'
      highlight-background-color='rgb(136,192,208)'
      highlight-colors-set=true
      highlight-foreground-color='rgb(46,52,64)'
      login-shell=false
      nord-gnome-terminal-version='0.1.0'
      palette=['#3B4252', '#BF616A', '#A3BE8C', '#EBCB8B', '#81A1C1', '#B48EAD', '#88C0D0', '#E5E9F0', '#4C566A', '#BF616A', '#A3BE8C', '#EBCB8B', '#81A1C1', '#B48EAD', '#8FBCBB', '#ECEFF4']
      use-custom-command=true
      use-system-font=false
      use-theme-background=false
      use-theme-colors=false
      use-theme-transparency=false
      use-transparent-background=true
      visible-name='Nord'

      [:8481259a-b760-4d77-a61e-9d0d255732ce/legacy/keybindings]
      zoom-in='<Primary>equal'

      [:8481259a-b760-4d77-a61e-9d0d255732ce/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9]
      audible-bell=false
      background-color='rgb(0,43,54)'
      background-transparency-percent=8
      custom-command='/usr/bin/fish'
      font='UbuntuMono Nerd Font Mono 19'
      foreground-color='rgb(131,148,150)'
      use-custom-command=true
      use-system-font=false
      use-theme-colors=false
      use-theme-transparency=false
      use-transparent-background=true

      [:default/legacy/keybindings]
      zoom-in='<Primary>equal'

      [:default/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9]
      audible-bell=false
      background-color='rgb(0,43,54)'
      background-transparency-percent=8
      custom-command='/usr/bin/fish'
      font='UbuntuMono Nerd Font Mono 19'
      foreground-color='rgb(131,148,150)'
      use-custom-command=true
      use-system-font=false
      use-theme-colors=false
      use-theme-transparency=false
      use-transparent-background=true

      [legacy/keybindings]
      zoom-in='<Primary>equal'

      [legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9]
      audible-bell=false
      background-color='rgb(0,43,54)'
      background-transparency-percent=8
      custom-command='/usr/bin/fish'
      font='UbuntuMono Nerd Font Mono 19'
      foreground-color='rgb(131,148,150)'
      use-custom-command=true
      use-system-font=false
      use-theme-colors=false
      use-theme-transparency=false
      use-transparent-background=true
  ansible.builtin.copy:
    dest: "/tmp/nord_terminal.dconf"
    force: false
    content: "{{ terminal_prefs }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Load terminal preferences
  ansible.builtin.shell: dconf load /org/gnome/terminal/legacy/profiles:/ < /tmp/nord_terminal.dconf
  register: result
  changed_when: false
  failed_when: result.rc != 0
