- name: Install GNOME packages
  become: yes
  ansible.builtin.package:
    name:
      - gnome-shell
      - gnome-shell-extensions
      - gnome-shell-extension-manager

- name: Dconf entries
  community.general.dconf:
    key: "{{ item.value.key }}"
    value: "{{ item.value.value }}"
  loop: "{{ dconf_entries | dict2items }}"

# Loading terminal preferences via the dconf module is tedious and hard to maintain,
# so using a .dconf file and loading that instead seems better
- name: Write terminal preferences to file
  ansible.builtin.copy:
    dest: "/tmp/nord_terminal.dconf"
    force: false
    content: "{{ gnome_terminal_prefs }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Load terminal preferences
  ansible.builtin.shell: dconf load /org/gnome/terminal/legacy/profiles:/ < /tmp/nord_terminal.dconf
  register: result
  changed_when: false
  failed_when: result.rc != 0
