- name: Download and insall ProtonVPN
  vars:
    file: "/tmp/protonvpn.deb"
  block:
    - name: Download ProtonVPN .deb file
      ansible.builtin.get_url:
        url: "https://repo.protonvpn.com/debian/dists/stable/main/binary-all/protonvpn-stable-release_1.0.4_all.deb"
        dest: "{{ file }}"
        checksum: "sha256:62a9d849835de8a5664cf95329458bf1966780b15cec420bf707b5f7278b9027"
        mode: 0755
    - name: Install ProtonVPN via .deb file
      ansible.builtin.apt:
        deb: "{{ file }}"

- name: Register ProtonVPN to autostart
  vars:
    autostart_script: |
      #!/usr/bin/env xdg-open 
      [Desktop Entry] 
      Type=Application
      Name=protonvpn
      Exec=bash -c "protonvpn-app"
      StartupNotify=false
      Terminal=false
  ansible.builtin.copy:
    content: "{{ autostart_script }}"
    dest: "{{ home_directory }}/.config/autostart/protonvpn.desktop"
    mode: 0644
