- name: Generate main SSH key
  community.crypto.openssh_keypair:
    path: "{{ ssh_key_file }}"
    type: ed25519

- name: Add references to config file
  community.general.ssh_config:
    user: "{{ username }}"
    host: "{{ item.value.host }}"
    hostname: "{{ item.value.hostname }}"
    identity_file: "{{ item.value.identity_file if 'identity_file' in item.value else ssh_key_file }}"
    add_keys_to_agent: true
    state: present
  loop: "{{ ssh_config_hosts | dict2items }}"
  when: ssh_config_hosts is defined
