- name: Generate main SSH key
  community.crypto.openssh_keypair:
    path: "{{ ssh_key_file }}"
    type: ed25519

- name: Add JacksonBox reference to config file
  community.general.ssh_config:
    user: "{{ username }}"
    host: "JacksonBox"
    hostname: "jacksonbox.local"
    identity_file: "{{ ssh_key_file }}"
    add_keys_to_agent: true
    state: present

- name: Add Raspberry Pi reference to config file
  community.general.ssh_config:
    user: "{{ username }}"
    host: "RaspberryPi"
    hostname: "raspberrypi.local"
    identity_file: "{{ ssh_key_file }}"
    add_keys_to_agent: true
    state: present
