- name: Generate main SSH key
  community.crypto.openssh_keypair:
    path: "{{ ssh_key_file }}"
    type: ed25519

- name: Add JacksonBox reference to config file
  community.general.ssh_config:
    user: "{{ username }}"
    host: "{{ hostvars['JacksonBox']['hostname'] }}"
    hostname: "{{ hostvars['JacksonBox']['domain'] }}"
    identity_file: "{{ ssh_key_file }}"
    add_keys_to_agent: true
    state: present

- name: Add RaspberryPi reference to config file
  community.general.ssh_config:
    user: "{{ username }}"
    host: "{{ hostvars['RaspberryPi']['hostname'] }}"
    hostname: "{{ hostvars['RaspberryPi']['domain'] }}"
    identity_file: "{{ ssh_key_file }}"
    add_keys_to_agent: true
    state: present
