personal:
  hosts:
    EvanAsus:
      ansible_connection: local

server:
  hosts:
    JacksonBox:
      ansible_host: jacksonbox.local
      ansible_port: 22
      ansible_user: ejackson
      ansible_connection: ssh
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519

raspberry_pi:
  hosts:
    RaspberryPi:
      ansible_host: raspberrypi.local
      ansible_port: 22
      ansible_user: ejackson
      ansible_connection: ssh
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519

docker:
  server:
  # raspberry_pi:

dotfiles:
  server:
  personal:

fish:
  server:
  personal:

github:
  personal:
  server:

ufw:
  server:
  # raspberry_pi:
