- name: Install flatpak
  become: yes
  ansible.builtin.package:
    name:
      - flatpak

- name: Add the Flathub Flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install Flatpaks
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop:
    - librewolf
    - com.brave.Browser
    - tv.plex.PlexDesktop
    - com.spotify.Client
    - com.github.tchx84.Flatseal
    - org.DolphinEmu.dolphin-emu
    - net.pcsx2.PCSX2

- name: Update Flatpaks
  ansible.builtin.shell:
    cmd: flatpak --user update --noninteractive
    executable: /bin/bash
  register: result
  changed_when: result != 0
