- name: Configure main user
  ansible.builtin.user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}"
    append: true
    shell: "{{ user_shell }}"
    update_password: on_create
  # passwordless sudo

- name: Suppress login message (hushlogin) for user
  ansible.builtin.file:
    path: "{{ home_directory }}/.hushlogin"
    mode: 0644
    owner: "{{ username }}"
    group: "{{ username }}"
    modification_time: preserve
    access_time: preserve
    state: touch

- name: Configure generic SSH client settings for user
  ansible.builtin.include_tasks: ssh_client.yml
