# System vars
hostname: EvanAsus
timezone: "America/Toronto"

# APT vars
apt_repositories:
  - "ppa:libretro/stable"
apt_packages:
  - audacity
  - ca-certificates
  - calibre
  - curl
  - dbus-x11
  - eog-plugins
  - gnupg
  - gnome-tweaks
  - libreoffice
  - make
  - nextcloud-desktop
  - pavucontrol
  - qbittorrent
  - retroarch
  - rpi-imager
  - solaar
  - steam
  - wget
  - vim
  - vlc

# User-level vars
username: ejackson
home_directory: "/home/ejackson"
user_shell: /usr/bin/fish
ssh_key_file: "/home/ejackson/.ssh/id_ed25519"
github_key_file: "/home/ejackson/.ssh/id_github_ed25519"
dotfiles_branch: personal

# Flatpaks
flatpaks:
  - librewolf
  - tv.plex.PlexDesktop
  - com.spotify.Client
  - com.github.tchx84.Flatseal
  - org.DolphinEmu.dolphin-emu
  - net.pcsx2.PCSX2

# Fonts
nerd_fonts_version: "v3.1.0"
fonts:
  ubuntu_mono:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/{{ nerd_fonts_version }}/UbuntuMono.zip"
    filename: "/tmp/UbuntuMono.zip"
