- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Run package-related tasks
  ansible.builtin.include_tasks: apt.yml

# TODO unattended upgrades

- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  ansible.builtin.reboot:
  when: reboot_required_file.stat.exists and trigger_reboots
