- name: Make ddclient directory
  become: true
  ansible.builtin.file:
    mode: 0644
    owner: "{{ services_users.ddclient.name }}"
    group: "{{ services_users.ddclient.groups }}"
    path: /etc/ddclient
    state: directory

- name: Create ddclient conf file
  become: true
  ansible.builtin.copy:
    mode: 0644
    owner: "{{ services_users.ddclient.name }}"
    group: "{{ services_users.ddclient.groups }}"
    dest: /etc/ddclient/ddclient.conf
    content: |
      ssl=yes
      syslog=yes
      use=web,web=dynamicdns.park-your-domain.com/getip
      protocol=namecheap
      server=dynamicdns.park-your-domain.com
      login={{ domain_name }}
      password={{ dynamic_dns_password }}
      {{ ddclient_domains }}

- name: Pull and run ddclient container
  community.docker.docker_container:
    name: ddclient
    pull: always
    state: started
    image: lscr.io/linuxserver/ddclient:latest
    restart_policy: unless-stopped
    env:
      PUID: "{{ services_users.ddclient.uid }}"
      PGID: "{{ services_users.ddclient.gid }}"
    volumes:
      - /etc/ddclient/ddclient.conf:/config/ddclient.conf
