- name: Add Docker apt public key
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 7EA0A9C3F273FCD8

- name: Run geerlingguy.pip role to install Docker pip package
  ansible.builtin.include_role:
    name: geerlingguy.pip

- name: Run geerlingguy.docker role to install and configure Docker
  ansible.builtin.include_role:
    name: geerlingguy.docker

- name: Add user to Docker group
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    groups: docker
    append: true
  register: add_to_docker_group_result
