- name: Disable SSH password auth
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    search_string: "PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
    validate: "sshd -T -f %s"
    mode: 0644
  register: sshd_config

- name: Restart SSH daemon
  ansible.builtin.service:
    name: sshd
    state: restarted
  when: sshd_config.changed
