# TODO Docker containers
- name: Open Minecraft (Java) port
  become: yes
  community.general.ufw:
    port: "25565"
    proto: tcp
    rule: allow

- name: Open Minecraft (Bedrock) port
  become: yes
  community.general.ufw:
    port: "19132"
    proto: tcp
    rule: allow
