- name: Create Nextcloud Docker network
  community.docker.docker_network:
    name: nextcloud_internal_network
    state: present
    internal: true

- name: Pull and run Nextcloud database container
  community.docker.docker_container:
    name: nextcloud-db
    pull: always
    state: started
    image: mariadb:latest
    restart_policy: unless-stopped
    command: "--transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed"
    env:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_ROOT_PASSWORD: "{{ nextcloud_db_password }}"
      MYSQL_PASSWORD: "{{ nextcloud_db_password }}"
    volumes:
      - nextcloud-db:/var/lib/mysql
    networks:
      - name: nextcloud_internal_network

- name: Pull and run Nextcloud application container
  community.docker.docker_container:
    name: nextcloud-app
    pull: always
    state: started
    image: nextcloud:latest
    restart_policy: unless-stopped
    env:
      NEXTCLOUD_TRUSTED_DOMAINS: "{{ nextcloud_domain_name }}" # required to get rid of "untrusted domains" error
      NEXTCLOUD_DATA_DIR: "/var/www/html/data"
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: "{{ nextcloud_admin_password }}"
      OVERWRITEPROTOCOL: https # required to authorize Nextcloud client apps
      MYSQL_HOST: nextcloud-db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: "{{ nextcloud_db_password }}"
      # The following settings allow this container to work with nginx-proxy and acme-companion
      VIRTUAL_HOST: "{{ nextcloud_domain_name }}"
      LETSENCRYPT_HOST: "{{ nextcloud_domain_name }}"
      VIRTUAL_PORT: "80"
    volumes:
      - nextcloud-app:/var/www/html
      - "{{ nextcloud_data_dir }}:/var/www/html/data"
    networks:
      - name: nextcloud_internal_network
      - name: "{{ nginx_network }}"
# TODO backups
