- name: Pull and run Wireguard (WG-Easy) container
  community.docker.docker_container:
    name: wireguard
    pull: always
    state: started
    image: ghcr.io/wg-easy/wg-easy
    restart_policy: "always"
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv4.ip_forward: 1
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - "{{ wireguard_port }}:51820/udp"
      - "{{ wireguard_webui_port }}:51821/tcp"
    env:
      WG_HOST: "{{ vpn_domain_name }}"
    volumes:
      - wireguard-data:/etc/wireguard

- name: Open Wireguard (UDP) port in UFW
  become: true
  community.general.ufw:
    port: "{{ wireguard_port }}"
    proto: udp
    rule: allow

- name: Open Wireguard GUI port in UFW
  become: true
  community.general.ufw:
    port: "{{ wireguard_webui_port }}"
    proto: tcp
    rule: allow
    direction: in
    src: "{{ item }}"
  loop: "{{ local_subnets }}"
