- name: Update APT packages
  become: true
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes

- name: Add custom APT repositories
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
  loop: "{{ custom_apt_repositories }}"
  when: custom_apt_repositories is defined and custom_apt_repositories != None

- name: Install packages
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ apt_packages }}"
  when: apt_packages is defined
