- name: Install paramiko package with pip (required by community.general.ssh_config)
  become: true
  environment:
    PIP_BREAK_SYSTEM_PACKAGES: "1"
  ansible.builtin.pip:
    name: paramiko

- name: Ensure SSH config file exists
  ansible.builtin.copy:
    dest: "{{ home_directory }}/.ssh/config"
    force: false
    content: ""
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
